---
title: "R Notebook"
output: 
---


```{r}
library(data.table)
library(tidyverse)
library(purrr)
library(expss)
theme_set(theme_classic())
library(ggpubr)
options(scipen=999)
library(eulerr)
library(patchwork)
library(BSgenome.Hsapiens.1000genomes.hs37d5)
```

```{r}
css_db_msd <- fread('../../data/processed/css_database_msd.tsv')
```


```{r}
css_db_msd_A <- css_db_msd[variant_category == 'A' & 
                             (abs(decoy_distance) <= 250) & !is.na(mes_decoy_alt)]

```




# Figure 6Ai


```{r}


rank <- css_db_msd_A[, .(donor_category, css_event_rank_250)]  %>%
  group_by(donor_category) %>% add_count(name = 'donor_category_count') %>%
  filter(!is.na(css_event_rank_250)) %>% group_by(donor_category,donor_category_count, css_event_rank_250) %>% 
  tally(name = 'count') %>% arrange(css_event_rank_250) %>%mutate(cumsum = cumsum(count)) %>% arrange(css_event_rank_250) %>%
  mutate(perc = cumsum / donor_category_count)
setDT(rank)

msd <- ggplot(rank, aes(x = css_event_rank_250, y = perc, color = donor_category)) + geom_line(size =1) + 
  geom_vline(xintercept = 4, linetype = 'dashed') + scale_x_reverse(breaks = seq(40, 0, -2)) + 
  labs(x = 'event rank in mis-splicing data', color = '',y = '') +
  scale_y_continuous(labels = scales::percent)+
  scale_color_manual(values = c('#EB9E00', 'grey')) +
  annotate("text", x =9, y = 0.15, 
           label = paste0(scales::percent(rank[css_event_rank_250 == 4 & donor_category == 'decoy'][1, perc], accuracy = 1), " of decoy 5'SS"), 
           color = 'black')+
  annotate("text", x = 9, y = 0.95, 
           label = paste0(scales::percent(rank[css_event_rank_250 == 4 & donor_category == 'cryptic'][1, perc], accuracy = 1), " of cryptic 5'SS"), 
           color = 'black') + 
  coord_cartesian(xlim = c(20, 0)) + theme(axis.text.x = element_text(angle = 45, hjust = 1))

```


# Figure 6Aii

```{r}
spliceai_delta <- css_db_msd_A[, .(donor_category, spliceai_decoy_delta = spliceai_decoy_alt - spliceai_decoy_ref)]  %>%
  group_by(donor_category) %>% add_count(name = 'donor_category_count')  %>% 
  group_by(donor_category,donor_category_count, spliceai_decoy_delta) %>% 
  tally(name = 'count') %>% arrange(-spliceai_decoy_delta) %>%mutate(cumsum = cumsum(count)) %>% arrange(spliceai_decoy_delta) %>%
  mutate(perc = cumsum / donor_category_count) 

setDT(spliceai_delta)


sai <- ggplot(spliceai_delta, aes(x = spliceai_decoy_delta, y = perc, color = donor_category)) + geom_line(size =1) + coord_cartesian(xlim = c(0, 1)) +
  scale_color_manual(values = c('#EB9E00', 'grey')) +
  geom_vline(xintercept = 0.1, linetype = 'dashed') +
  annotate("text", x = 0.1 + 0.15, y = 0.05, 
           label = paste0(scales::percent(spliceai_delta[spliceai_decoy_delta >= 0.1 & donor_category == 'decoy'][1, perc], accuracy = 1), " of decoy 5'SS"), 
           color = 'black')+
  annotate("text", x = 0.1 + 0.15, y = 0.84, 
           label = paste0(scales::percent(spliceai_delta[spliceai_decoy_delta >= 0.1 & donor_category == 'cryptic'][1, perc], accuracy = 1), " of cryptic 5'SS"), 
           color = 'black') +
  scale_x_continuous(breaks = seq(0, 1, 0.1)) + labs(x = 'SAI score decoy alt', color = '', y = '') +
  scale_y_continuous(labels = scales::percent)+ theme(axis.text.x = element_text(angle = 45, hjust = 1))


```


# Figure 6Aiii

```{r}
venn <-css_db_msd_A[, .(donor_category, css_event_rank_250, 
                        spliceai_decoy_delta = spliceai_decoy_alt - spliceai_decoy_ref)] %>%
  mutate(in_msd = ifelse(css_event_rank_250 > 4 | is.na(css_event_rank_250), 0, 1),
         spliceai_01 = ifelse(spliceai_decoy_delta >= 0.1, 1, 0),
         cryptic = ifelse(donor_category == 'cryptic', 1, 0),
         decoy = 1) %>% dplyr::select('in_msd', 'cryptic', 'decoy', 'spliceai_01')


vennp <- plot(euler(venn), counts = TRUE, fills = list(fill = c('#2DB5ED','#EB9E00', 'grey', '#0E76A1'), alpha = 0.5) ) 
#venn %>% group_by(cryptic, in_msd, spliceai_01) %>% tally()
```

```{r}
left <- ggarrange(msd,sai, nrow = 2, common.legend = T, legend = 'bottom')

```

# Figure 6b

```{r}
css_db_msd_BC <- css_db_msd[variant_category != 'A' & donor_category == 'cryptic']

css_db_msd_BC[, ref_ES := ifelse(substr(decoy_ref_seq,5,6) %in% c('GT', 'GC'), 1, 0)]
css_db_msd_BC[, in_msd := ifelse(is.na(css_event_rank), 'Not in MSD', 
                                 ifelse(css_event_rank <= 4, 'In top 4','In msd')) ]

css_db_msd_BC[, sai_01 := ifelse((spliceai_decoy_alt - spliceai_decoy_ref) >= 0.1, 
                                 'SAI >= 0.1', 'SAI < 0.1')]

#css_db_msd_BC %>% group_by(ref_ES) %>% tally()


```



```{r}
saiBC_ES <- css_db_msd_BC %>% group_by(ref_ES,sai_01) %>% tally()%>%
  filter(ref_ES == 1) %>%
  mutate(perc = n / sum(n)) %>%
  ggplot(aes(x = '', y = perc, fill = factor(sai_01))) + scale_fill_manual(values = c('grey', '#EB9E00'))+  theme_void() +
  geom_bar(width = 1, stat = "identity")+ coord_polar("y", start=0) +
  theme(axis.text.x=element_blank()) +
  geom_text(aes(label = paste0(sai_01, '\n', scales::percent(perc, accuracy= 2))), position = position_stack(vjust = .5)) +
  theme(legend.position = 'none') 

saiBC <- css_db_msd_BC %>% group_by(ref_ES,sai_01) %>% tally()%>%
  filter(ref_ES == 0) %>%
  mutate(perc = n / sum(n)) %>%
  ggplot(aes(x = '', y = perc, fill = factor(sai_01))) + scale_fill_manual(values = c('grey', '#EB9E00'))+  theme_void() +
  geom_bar(width = 1, stat = "identity")+ coord_polar("y", start=0) +
  theme(axis.text.x=element_blank()) +
  geom_text(aes(label = paste0(sai_01, '\n', scales::percent(perc, accuracy= 2))), position = position_stack(vjust = .5)) +
  theme(legend.position = 'none') 
```


```{r}
BC <- css_db_msd_BC %>% group_by(ref_ES) %>% tally() %>%
  mutate(perc = n / sum(n)) %>%
  ggplot(aes(x = '', y = perc, fill = factor(ref_ES))) + scale_fill_manual(values = c('grey', '#0E76A1'))+  theme_void() +
  geom_bar(width = 1, stat = "identity")+ coord_polar("y", start=0) +
  theme(axis.text.x=element_blank())+ 
  geom_text(aes(label = paste0(ref_ES, '\n', scales::percent(perc, accuracy= 2))), position = position_stack(vjust = .5)) +
  theme(legend.position = 'none')

msdBC_ES <- css_db_msd_BC %>% filter(ref_ES == 1) %>% group_by(in_msd) %>% tally() %>%
  mutate(perc = n / sum(n)) %>%
  ggplot(aes(x = '', y = perc, fill = factor(in_msd))) + scale_fill_manual(values = c('#F0C100','#EB9E00', 'grey'))+  theme_void() +
  geom_bar(width = 1, stat = "identity")+ coord_polar("y", start=0) +
  theme(axis.text.x=element_blank()) +
  geom_text(aes(label = paste0(in_msd, '\n', scales::percent(perc, accuracy= 2))), position = position_stack(vjust = .5)) +
  theme(legend.position = 'none')

bottom <- ggarrange(saiBC, plot_spacer(),saiBC_ES,msdBC_ES, nrow = 1, ncol = 4)
```

```{r}
A <- ggarrange(left, vennp, widths = c(1,1))
B <- ggarrange(BC, bottom, nrow = 2, heights = c(1, 1.2))
ggarrange(A,B, nrow = 1)
ggsave('../figures/figure_6.pdf', width = 11, height = 5)
```

